### ISSUE TITLE
Expose queue parameters

### ISSUE THREAD

**Issue by oz** [flivni/batch_queue#2]
Hey there!

I really like this little gem of yours, and have been using it in various projects for a long time... It's simple and just works. Nothing to fix. Thanks! 🙇🏻 

I'd like to be able to expose the max-size of a BatchQueue instance in some logs. Do you think we could have an `attr_reader` to expose a few of the initialize parameters? I'm thinking of these 2:

- `@max_batch_size`, and maybe
- `@max_interval_seconds`.

I really "need" the former to be able to log the batch's size VS the max size. The latter would be for completeness. Let me know if I can help, or if you'd accept a small PR for this.

(Unrelated, please do merge #1, so that people aren't stuck with an old version of Rake 🙏🏻).

**Comment by flivni** [comment]
@oz --

I guess I missed your post until today. I just released 1.1.0 which includes your requests and also a hook for error handling.

And thanks for your kind words.
